services:
  n8n:    
    # image: n8nio/n8n:latest # Commented out the image line and use build instead
    build:
      context: .
      dockerfile: Dockerfile
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://localhost:5678/
      - NODE_FUNCTION_ALLOW_EXTERNAL=*  # Important for custom functionality
    volumes:
      - /home/andrei/.n8n_vol:/home/node/.n8n
      - /home/andrei/.n8n_user_data:/home/node/user_data

